version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - redis